### ISSUE TITLE
PhotoPost by using URL

### ISSUE THREAD

**Issue by selvakottur** [tumblr/jumblr#53]
Image posting is not working. Take look at my question in stackoverflow.

http://stackoverflow.com/questions/28087464/tumblr-photo-posting-by-using-jumblr/28087551#28087551

**Comment by eneim** [comment]
The main problem might be this:

'''01-22 16:25:44.929: E/AndroidRuntime(10082): Caused by: org.scribe.exceptions.OAuthConnectionException: There was a problem while creating a connection to the remote service.'''

And I found something related:

http://stackoverflow.com/questions/17865468/scribe-java-and-async-request-in-android-4

As said, jumblr uses scribe library for their task (I suppose, please fix), which should happen on the main thread. Meanwhile, you are execute your task by an Asynctask which suppose to happen in background (your call to PublishPicture.doInBackground())

Please consider to post your url from inside the onPostExecute method, or something that will happen on main thread. For example, return the url from doInBackground, and inside onPostExecute, use that url to post to tumblr.

**Comment by selvakottur** [comment]
I changed below code from doInBackground to onPostExecute. 

                                String imgUrl = "http://dummyimage.com/300.png/09f/fff";
				photoPost1.setCaption("sample");
				photoPost1.setSource(imgUrl);
				//photoPost1.setPhoto(new Photo(imgUrl));
				//photoPost1.setLinkUrl(imgUrl);
				photoPost1.save();

Still i am getting same error.

**Comment by eneim** [comment]
What is the difference between ```setSource``` and ```setLinkUrl```? 

Furthermore,　there are 2 things you may want to confirm: is your Oauth process success and your use of asyntask. If they are all Ok,  I would like to have a test and will continue this discussion in Stackoverflow question.

**Comment by selvakottur** [comment]
I am sure that my Oauth process getting success. Because i tested to post images as FILE.
	 PhotoPost photoPost = client.newPost(client.user().getName(),
				 PhotoPost.class);
				 File file = new File(picturePath);
				 photoPost.setPhoto(new Photo(file));
				 photoPost.save();

This is working fine in doInBackground as well as in  onPostExecute.

**Comment by KevinTCoughlin** [comment]
@selvakottur, I was able to create & save a new `PhotoPost` with the following code once I authenticated.

``` java
    final String source = "<YOUR IMAGE URL HERE>";
    final PhotoPost post = client.newPost("<AUTHENTICATED BLOG NAME>", PhotoPost.class);
    post.setSource(source);
    post.save();
```

Are you still having this issue?

**Comment by KevinTCoughlin** [comment]
Closing as I was unable to reproduce the issue and have not heard back.

**Comment by mittalharsh54** [comment]
I am facing the same issue. pls help me with this.

**Comment by KevinTCoughlin** [comment]
@mittalharsh54 can you share the code that you're having the issue with?

**Comment by mittalharsh54** [comment]
hey @KevinTCoughlin  thanks for reply, I executed the photo upload code in async task and then it did the work. I  think i was executing it directly so it was showing error. Thanks
